package kaboom

data class LargeObject(
    val longOne: Long,
    val longTwo: Long,
    val longThree: Long,
    val longFour: Long,
    val longFive: Long,
    val longSix: Long,
    val longSeven: Long,
    val longEight: Long,
    val longNine: Long,
    val longTen: Long,
    val longEleven: Long,
    val longTwelve: Long,
    val longThirteen: Long,
    val longFourteen: Long,
    val longFifteen: Long,
    val longSixteen: Long,
    val longSeventeen: Long,
    val longEighteen: Long,
    val longNineteen: Long,
    val longTwenty: Long,
    val longTwentyOne: Long,
    val longTwentyTwo: Long,
    val longTwentyThree: Long,
    val longTwentyFour: Long,
    val longTwentyFive: Long,
    val longTwentySix: Long,
    val longTwentySevent: Long,
    val longTwentyEight: Long,
    val longTwentyNine: Long,
    val longThirty: Long
)
